### ISSUE TITLE
"Unix Modular Synth"

### ISSUE THREAD

**Issue by mxmilkiib** [OpenMusicKontrollers/shells_bells.lv2#2]
I've just seen drobilla's older [Unix Modular Synth](http://drobilla.net/2007/04/28/unix-modular-synth.html) post, and I couldn't help think of this plugin.

I'm stumped as to what mechanism could be used to achieve such though..

**Comment by ventosus** [comment]
Thanks for the inspiration !

Hmm, instead of an interactive shell like in shells_bells, this could be a code-based plugin, which runs the code (be it shell, python, whathever) in a DSP worker thread. Events (e.g. MIDI) would be written/read to/from stdin/stdout or special file descriptors, or shared memory, or ...

Sounds like fun

**Comment by ventosus** [comment]
As this is an idea for a new plugin and has nothing to do with shells_bells, I'll close it.
